# Preparação dos dados

In [ ]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/Primeiros_passos_pytorch/main/sementes.csv'

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

Área  Perímetro  Compacidade  Comprimento  Largura  Assimetria  \
0  15.26      14.84      871.000        5.763    3.312       2.221   
1  14.88      14.57        8.811        5.554    3.333       1.018   
2  14.29      14.09      905.000        5.291    3.337       2.699   
3  13.84      13.94        8.955        5.324    3.379       2.259   
4  16.14      14.99        9.034        5.658    3.562       1.355   

   Comprimento do sulco  Espécie  
0                 5.220        0  
1                 4.956        0  
2                 4.825        0  
3                 4.805        0  
4                 5.175        0

In [ ]:
df['Espécie'].unique()

array([0, 1, 2])

In [ ]:
# Separando as features e a coluna alvo
X = df.drop('Espécie', axis=1).values
y = df['Espécie'].values

In [ ]:
# Dividindo em dados de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Normalizando os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Construção do modelo

In [ ]:
# Construção do modelo
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(16, activation='relu'),  # Camada oculta com 16 neurônios
    tf.keras.layers.Dense(8, activation='relu'),  # Outra camada oculta com 8 neurônios
    tf.keras.layers.Dense(3, activation='softmax')  # Camada de saída com 3 neurônios (uma para cada classe)
])

# Resumo do modelo
model.summary()


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                     │ (None, 16)                  │             128 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 8)                   │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 3)                   │              27 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 291 (1.14 KB)

 Trainable params: 291 (1.14 KB)

 Non-trainable params: 0 (0.00 B)

# Propagação

In [ ]:
# Realizando a propagação (forward pass)
predictions = model(X_test)

# Exibindo as previsões para as primeiras 5 amostras
print("Previsões (antes do treinamento):\n", predictions.numpy()[:5])


Previsões (antes do treinamento):
 [[0.5551747  0.40294152 0.0418837 ]
 [0.4009459  0.33201128 0.26704273]
 [0.64143336 0.2842082  0.07435836]
 [0.36398727 0.34043762 0.29557508]
 [0.3857329  0.32722858 0.2870385 ]]


In [ ]:
# Convertendo as previsões para a classe com maior probabilidade
predicted_classes = tf.argmax(predictions, axis=1)

In [ ]:
# Calculando a acurácia
accuracy = accuracy_score(y_test, predicted_classes)
accuracy

0.2619047619047619

# Treinamento

In [ ]:
# Compilando o modelo
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
# Treinando o modelo
history = model.fit(X_train, y_train, epochs=50, validation_data=(X_test, y_test))

Epoch 1/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.6735 - loss: 0.7712 - val_accuracy: 0.7143 - val_loss: 0.9326
Epoch 2/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6447 - loss: 0.7505 - val_accuracy: 0.7143 - val_loss: 0.8952
Epoch 3/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7068 - loss: 0.7091 - val_accuracy: 0.7381 - val_loss: 0.8468
Epoch 4/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6552 - loss: 0.7059 - val_accuracy: 0.7143 - val_loss: 0.8220
Epoch 5/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6566 - loss: 0.6773 - val_accuracy: 0.7143 - val_loss: 0.7985
Epoch 6/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6898 - loss: 0.6440 - val_accuracy: 0.7143 - val_loss: 0.7600
Epoch 7/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6538 - loss: 0.6366 - val_accuracy: 0.7143 - val_loss: 0.7162
Epoch 8/50
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6714 - loss: 0.6157 - val_accuracy: 0.7143 - val_loss: 0.6606
Epoch

In [ ]:
# Avaliando o modelo no conjunto de teste
model.evaluate(X_test, y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8686 - loss: 1.2375 


[1.1308863162994385, 0.8809523582458496]